apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

commonLabels:
  app: my-deployment

vars:
  - name: image
    objref:
      kind: ConfigMap
      name: my-config
      apiVersion: v1
    fieldref:
      fieldpath: data.image
